[package]
name = "hex_editor"
version.workspace = true
edition.workspace = true
publish = false
description = "Standalone authoring tool for palette-backed hex-voxel objects."

[dependencies]
atomicwrites = { workspace = true }
bevy = { workspace = true }
bevy_egui = { workspace = true }
hex_assets = { workspace = true }
hex_core = { workspace = true }
ron = { workspace = true }
serde = { workspace = true }

[lints]
workspace = true
